name: pos_flutter_app
description: Modern POS Showroom Flutter Application

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  material_design_icons_flutter: ^7.0.7296
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # State Management
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  
  # Navigation
  go_router: ^13.0.0
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # Forms & Validation
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  
  # Utils
  intl: ^0.18.1
  logger: ^2.0.2+1
  equatable: ^2.0.5
  
  # Charts & Data Visualization
  fl_chart: ^0.66.0
  
  # Image & File Handling
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  
  # Animations
  lottie: ^2.7.0
  
  # Loading & Progress
  flutter_spinkit: ^5.2.0
  
  # Toast & Snackbar
  fluttertoast: ^8.2.4
  another_flushbar: ^1.12.30

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600